const fs=require('fs');const{setup,assert}=require('./helpers.cjs');
(async()=>{const t=await setup(true),{page,state,run,poi,act,walk}=t;
async function fixture(code){await page.reload();await page.setContent(fs.readFileSync('index.html','utf8').replace(/<script[^>]*><\/script>/g,''));await page.addStyleTag({content:fs.readFileSync('style.css','utf8')});await page.addScriptTag({content:fs.readFileSync('data.js','utf8')});await page.addScriptTag({content:fs.readFileSync('game.js','utf8').replace('updateUI();requestAnimationFrame(frame);',code+"started=true;profile.sound=false;$('welcome').hidden=true;updateUI();requestAnimationFrame(frame);" )});await run(100);}
await fixture("window.networkSamples=Array.from({length:18},(_,n)=>[makeMainTrain(n,1),makeMainTrain(n,-1)]).flat();scene='keioPlatform';mainStation=15;");const samples=await page.evaluate(()=>networkSamples);for(const tr of samples){assert.equal(tr.calls[0].station,tr.dir===1?0:tr.path[0]);assert.equal(tr.calls.at(-1).station,tr.dir===1?tr.path.at(-1):0);for(let i=1;i<tr.calls.length;i++)assert.ok(tr.calls[i].arr>=tr.calls[i-1].dep, tr.id+' monotonic');if(tr.route==='hashimoto')assert.ok(!tr.path.includes(16));else assert.ok(!tr.path.includes(38));if(tr.service.id==='express'&&tr.route==='hashimoto'){assert.equal(tr.calls.find(c=>c.station===45).stop,false);assert.equal(tr.calls.find(c=>c.station===46).stop,true);}if(tr.service.id==='rapid'||tr.service.id==='section')for(const c of tr.calls.filter(c=>c.station>=38))assert.ok(c.stop);if(tr.service.id==='liner')assert.ok(!tr.calls.find(c=>c.station===15).stop);}
assert.ok(!(await state()).pois.some(p=>p.id==='mainLink'));console.log('PASS 36 services: branches, direction, monotonic times, stop patterns, no Chofu transfer');
await fixture("mainStation=0;mainDirection=1;mainPaid=true;mainEntry=0;scene='keioPlatform';player={x:600,y:450};const chosen=makeMainTrain(15,1);time=chosen.calls[0].arr+2;");await act();assert.equal((await state()).scene,'keioPlatform');await poi('mainLiner');await page.locator('[data-do="mainLinerBuy"]').click();assert.equal((await state()).profile.coins,700);await walk('mainTrain');await act();assert.equal((await state()).scene,'keioCar');assert.equal((await state()).main.ride.service,'liner');assert.equal((await state()).profile.linerTicket,null);await page.locator('[data-speed="4"]').click();let before=(await state()).time;await run(1000);assert.ok(Math.abs((await state()).time-before-4)<.2);await page.screenshot({path:'artifacts/v10-speed-mobile.png'});const rects=await page.evaluate(()=>['speedControls','action','joystick'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}}));assert.ok(rects[0].x>=0&&rects[0].x+rects[0].w<=390);assert.ok(rects[0].y+rects[0].h<=rects[1].y);console.log('PASS liner rejects no ticket, accepts and consumes ticket; mobile 4x');
await fixture("mainRide=makeMainTrain(15,-1);scene='keioCar';mainStation=48;time=mainRide.calls.find(c=>c.station===46).arr+2;player={x:600,y:605};");await act();assert.equal((await state()).scene,'keioCar');assert.equal((await state()).main.ride.station,46);console.log('PASS inbound Liner intermediate station is boarding-only');
await fixture("mainRide=makeMainTrain(0,1);scene='keioCar';time=2;clockOffset=480-900-time/2;player={x:100,y:605};");assert.equal((await state()).seating.slots.filter(s=>s.occupied).length,10);console.log('PASS through ordinary train peak crowds');
await fixture("mainStation=26;mainEntry=45;keioOrigin='hori';mainPaid=true;scene='keioHall';player={x:600,y:280};");await poi('mainLink');await poi('passageExit');assert.equal((await state()).scene,'zooHall');assert.equal((await state()).zoo.paid,true);await poi('mainLink');await poi('passageExit');assert.equal((await state()).main.station,26);assert.equal((await state()).main.origin,'hori');console.log('PASS Takahatafudo zoo connection retains original IC journey');await t.finish();})().catch(e=>{console.error(e);process.exit(1)});
